# Generated by Django 5.0.3 on 2024-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddata',
            name='action',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
