# Generated by Django 5.0.3 on 2024-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0003_alter_importeddata_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeddata',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
